shoe_db = [
    {"title": "Nike Air Monarch IV", "brand": "Nike", "category": "sneakers"},
    {"title": "Nike Air Vapormax Plus", "brand": "Nike", "category": "sneakers"},
    {"title": "Nike Waffle One Sneaker", "brand": "Nike", "category": "sneakers"},
    {"title": "Nike Running Shoe", "brand": "Adidas", "category": "sneakers"},
    {"title": "Flat Slip On Pumps", "brand": "Vans", "category": "flats"},
    {"title": "Knit Ballet Flat", "brand": "Adidas", "category": "flats"},
    {"title": "Loafer Flats", "brand": "Vans", "category": "flats"},
    {"title": "Nike Zoom Freak", "brand": "Nike", "category": "sneakers"},
    {"title": "Nike Men's Sneaker", "brand": "Adidas", "category": "sneakers"},
    {"title": "PUMA BLACK-OCE", "brand": "Puma", "category": "sneakers"},
    {"title": "Pacer Future Sneaker", "brand": "Puma", "category": "sneakers"},
    {"title": "Unisex-Adult Super", "brand": "Puma", "category": "sneakers"},
    {"title": "Roma Basic Sneaker", "brand": "Puma", "category": "sneakers"},
    {"title": "Pacer Future Doubleknit", "brand": "Puma", "category": "sneakers"},
    {"title": "Fusion Evo Golf Shoe", "brand": "Puma", "category": "sneakers"},
    {"title": "Rainbow Chex Skate", "brand": "Vans", "category": "sandals"},
    {"title": "Low-Top Trainers", "brand": "Vans", "category": "sandals"},
    {"title": "Vans Unisex Low-Top", "brand": "Vans", "category": "sandals"},
    {"title": "Classic Bandana Sneakers", "brand": "Nike", "category": "sandals"},
    {"title": "Chunky High Heel", "brand": "Vans", "category": "heels"},
    {"title": "Slip On Stiletto High Heel", "brand": "Puma", "category": "heels"},
    {"title": "DREAM PAIRS Court Shoes", "brand": "Nike", "category": "heels"},
    {"title": "Low Mid Block Heels", "brand": "Nike", "category": "heels"},
    {"title": "Chunky High Heel", "brand": "Adidas", "category": "heels"},
    {"title": "Amore Fashion Stilettos", "brand": "Adidas", "category": "heels"},
    {"title": "Bridal Sandals Glitter", "brand": "Adidas", "category": "heels"},
    {"title": "Wedding Prom Bridal", "brand": "Adidas", "category": "flats"},
    {"title": "Nike dunks (ginni special)", "brand": "Nike", "category": "Sneakers"},
]
